#!/bin/sh

# http://tldp.org/LDP/abs/html/options.html
set -o errexit # Abort script at first error, when a command exits with non-zero status

status=0

myDir=`dirname $0`
logDir=$myDir/log

# List of scripts to run
scripts='bash/setup-bash vim/setup-vim apt/update apt/install-curl'

# Run scripts using run-script
for relFile in $scripts ; do

  if [ ! -f $logDir/completed/$relFile ] ; then

    printf 'Running %s...\n' $relFile
    set +o errexit
    $myDir/run-script $relFile
    status=$?
    set -o errexit

    if [ x$status != x0 ] ; then

      break
    fi
    printf 'Finished %s.\n' $relFile
  fi
done

# Clean up the log directory
# http://unix.stackexchange.com/questions/8430/how-to-remove-all-empty-directories-in-a-subtree
find $logDir -type d -empty -delete

exit $status

