#!/bin/sh

dir=`dirname $0`

. "$dir"/step

step "$dir"/bash/setup-bash
step "$dir"/vim/setup-vim
step "$dir"/apt/update
step "$dir"/apt/install-vim
step "$dir"/apt/install-git
step "$dir"/git/setup-git
step "$dir"/vim/install-vundle
