#!/usr/bin/env dash

dir=/vagrant/setup

. "$dir"/step

cd ~/git/agconti/kaggle-titanic

step virtualenv env
. env/bin/activate

# `pip install -r requirements.txt` does not work
# http://stackoverflow.com/a/11015904
for package in xgboost jupyter `cat requirements.txt | sed 's/=.//'`
do
  step pip install "$package"
done
