#!/usr/bin/env dash

dir=/vagrant/setup

. "$dir"/step

step cp "$dir"/bash/.bashrc ~
step sudo apt-get update
step cp "$dir"/git/.gitconfig "$dir"/git/.gitignore_global ~
step git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
step cp "$dir"/vim/.vimrc ~
step_nolog vim +:PluginInstall +:qa

