#!/usr/bin/env dash

step_file=${0}-current-step.txt
step_log_file=${0}-log.txt

step_current=1

if [ $# -ge 1 ] ; then

  step_start_at=$1
  shift
else

  if [ -r "$step_file" ]
  then step_start_at=`cat "$step_file"`
  else step_start_at=1
  fi
fi

log(){
  local file message

  file="$1"
  shift
  message=
  while [ $# -ge 1 ] ; do

    message="$message $1"
    shift
  done

  echo [`date +%s`] $message 1>>"$file"
}

step() {
  if test $step_current -eq $step_start_at ; then

    log "$step_log_file" $@
    echo $@
    if "$@" 2>&1 | tee -a "$step_log_file" ; then

      step_current=$(($step_current + 1))
      step_start_at=$step_current
      echo $step_current 1>"$step_file"
    else

      echo $@
      echo ERROR!!
      exit 1
    fi

  else

    step_current=$(($step_current + 1))
  fi
}

step_nolog() {
  if test $step_current -eq $step_start_at ; then

    log "$step_log_file" $@
    echo $@
    if "$@" 2>/dev/null 1>&2 ; then

      step_current=$(($step_current + 1))
      step_start_at=$step_current
      echo $step_current 1>"$step_file"
    else

      echo $@
      echo ERROR!!
      exit 1
    fi

  else

    step_current=$(($step_current + 1))
  fi
}

